disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - force_cast
  - cyclomatic_complexity
  - nesting
  - large_tuple

identifier_name:
  min_length: 2
  excluded:
    - e